services:
  src:
    container_name: src
    image: src-image
    ports:
      - 8000:8000
    volumes:
      - chess-volume:/app

  controller:
    container_name: controller
    image: controller-image
    ports:
      - 9000:9000
    volumes:
      - chess-volume:/app

  logic:
    container_name: logic
    image: logic-image
    ports:
      - 9001:9001
    volumes:
      - chess-volume:/app

  persistence:
    container_name: persistence
    image: persistence-image
    ports:
      - 9002:9002
    volumes:
      - chess-volume:/app

  rest:
    container_name: rest
    image: rest-image
    ports:
      - 9003:9003
    volumes:
      - chess-volume:/app

  ui:
    container_name: ui
    image: ui-image
    ports:
      - 9004:9004
    volumes:
      - chess-volume:/app

  utils:
    container_name: utils
    image: utils-image
    ports:
      - 9005:9005
    volumes:
      - chess-volume:/app

volumes:
  chess-volume:
