name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"
      - name: compile
        run: sbt compile

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt "; project controller; +clean; +coverage; +test; +coverageReport"
          sbt "; project logic; +clean; +coverage; +test; +coverageReport"
          sbt "; project persistence; +clean; +coverage; +test; +coverageReport"
      - name: Create Coverage Report
        run: |
          sbt "; project controller; coverageAggregate; coveralls"
          sbt "; project logic; coverageAggregate; coveralls"
          sbt "; project persistence; coverageAggregate; coveralls"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
